[libraries]

lib.files = [
"write_back.vhd",
"mydefinitions.vhd",
"memory_accTest.vhd",
"memory_acc.vhd",
"fetchTest.vhd",
"fetchDecodeTest.vhd",
"fetch.vhd",
"executeTest.vhd",
"execute.vhd",
"decodeTest.vhd",
"decode.vhd",
"memorySim/rom.vhd",
"memorySim/ramIO.vhd",
"memorySim/ramB.vhd",
"memorySim/procTest.vhd",
"memorySim/memPkg.vhd",
]
